spark.boot.catalogs {
  analytics_iceberg {
    type = "iceberg-hive"
  }

  archive_iceberg {
    type = "iceberg-hive"
  }

  analytics_hive {
    type = "kyuubi-hive"
  }

  archive_hive {
    type = "kyuubi-hive"
  }
}
